# 测试环境配置
redis:
  host: 'redis'
  port: 6379
  password: ""
  url: ""
  maxIdle: 10
  maxActive: 10

mysql:
  host: 'mysql'
  port: 3306
  user: "root"
  password: "666"

env:
  mode: "develop"
  TokenSecret: "123456789"
  TokenMaxAge: 604800
  PassSalt: "hard to guess"
